train_file: ['/data/vqa_train.json',
             '/data/vqa_val.json']
             
test_file: ['/data/vqa_test.json']
answer_list: '/data/answer_list.json'

vqa_root: '/data/mscoco' #train2014/

image_res: 384
batch_size_train: 4
batch_size_test: 4
k_test: 128

alpha: 5
epsilon: 8
num_iters: 10
sample_num: 10

distill: True
warm_up: True

eos: '[SEP]'

bert_config: './config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 8, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}
